appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 0T/C2ACTuitfXxjTgGRhFNHouqhsbxP1VxeWGHB7uiVqYkzgmdBnGNrGUxqKhlJ4LrBsOGrHoN7c+6LcmvTzNxyG7b64heLj6kwBX2CAgt5MJVpqBdxGsgodspHh2IWyGI7aHV3C4FF5ENzebNll7rWUK6VLvY2wpr6+nskHtriLOMdFwyI6OeMS8H4pIwVO1dYfH6XhEYa7NQvsI1b6PKnBaHCDMV7u2dp2Do2uCPGxHKFT+spj1/f6tMbxvVYDA8yaVcqpTvhYkI4E0cD00lino/BTLX0HHdxlPecDFyj3oB6Sop5Zx3JrQ+/NEHhljU0whCr7ms3o9wyiZPHAbVl4xhjcsDDBKJ8K3oM5317lrnADusH6p+c/TUjMdS2kELCVGXi6MgQL2BsUuIYTsmImETOlShF5F0Urq7wzNrV9Y5AMMxHZrxVN85Vi7Swb5TB0Q/AhIGT1hwCKQUIVbGCUAEFcwNGoehlRV0y1jv28c0osfWK9Z1DBtiHCWGU/N2Pt+LN0aU1LPcw/p8fdXBjsZlxN6PoIBT78bRM7OCOpuZekvHUTzbyytwGME6WsgVNKeVi4GOjD40UYNsKVdL3SqfCrd5Ec1b/7hMMC9+iMnwBunLLrBeTlKgvwLQh8wSsNDpXQTsSsfO0kpsATLl1nLe66Eb6la16FKEYCiFo=
conda_forge_output_validation: false
