travis:
  secure:
    BINSTAR_TOKEN: D6XseajvzoMKsQCeuKp5nGfkfpbvrmvr8wOFqmEPsHmOoR7+Ejwj2KmBHU/6Pgx4Qg20TfQXjSjpnVGy5iqkoykx1AYzom26MT4v/dEplc20VNdtYFxHVHvn/J8biynfFlFkoFSPUVKtMGreK9Paq1DJdV81O6sU19a64DNfOkakkJ7MxqQcY/iMX9bvnNxPl2ORwQ7TnjHqEd9NYAN7o/ulgG9w6O/H9H94iVEan7cSXzDJRKVyMxsRzz2y3MbonKYFHTXhwh0xt+PA3h+FIoG2olA0v4myXDBCIg1mO9vWbt5BWlZBJ9PiZ5XX9YcJlKxWQCVwHqNZ4BFE3gAobwOSo0BgK0HY4gsljAgJgub7ACo7OOpQoD0vEuRepS0qHKpKhvPt9JR1DoaPvOLtpBaCU5dc6KFdY4dKIiBXtAI/NKTzt3UkTn8jDljfSGEWD026l+t7F+Yp951ZKc9At2oPjtIZnjMTTI+6dlYrCk1ugRZpw3MFj/dVAiDmp2if6iT+jm7TENuJpPGniJ8H5zIvUkTJK3dAxJFRwKwv22EIo4an/oOWXdYuBArJh81n6HOZg9WoO0fSjf5SugjxhMYUW41yxmxR1g/YuFUGHsoP9DYbjNWttl94LykQbh+usGyPNS/GgnvqHsDB0f6uFGhyniop08S3qiIIe5ymy78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
